### ISSUE TITLE
module 'GWForge.utils' has no attribute 'reference_prior_dict'

### ISSUE THREAD

**Issue by divyajyoti09** [koustavchandra/gwforge#1]
While generating population using `gwforge_population --config-file bbh.ini --output-file test.h5  --source-type bbh`
the following error occurs:
```
2024-10-18 13:41:09 Generating mass samples
/Users/gravity/opt/anaconda3/envs/gwforge_18Oct24/lib/python3.9/site-packages/gwpopulation/models/mass.py:598: RuntimeWarning: invalid value encountered in divide
  p_q /= self.norm_p_q(beta=beta, mmin=mmin, delta_m=delta_m)
Traceback (most recent call last):
  File "/Users/gravity/opt/anaconda3/envs/gwforge_18Oct24/bin/gwforge_population", line 88, in <module>
    mass_samples = m.sample()
  File "/Users/gravity/opt/anaconda3/envs/gwforge_18Oct24/lib/python3.9/site-packages/GWForge/population/mass.py", line 78, in sample
    mass_prior = bilby.gw.prior.BBHPriorDict(dictionary=utils.reference_prior_dict)
AttributeError: module 'GWForge.utils' has no attribute 'reference_prior_dict'
```

**Comment by divyajyoti09** [comment]
Maybe this line 
```
mass_prior = bilby.gw.prior.BBHPriorDict(dictionary=utils.reference_prior_dict)
```
in `GWForge/population/mass.py` can be replaced with 
```
mass_prior = bilby.gw.prior.BBHPriorDict()
``` 
if we want to use the default priors provided by bilby.

**Comment by koustavchandra** [comment]
Solved in the recent push.
